from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class ReupBackend(Protocol):
    backend_name: str

    def required_local_paths(self) -> list[Path]: ...

    def get_channels(self) -> list[str]: ...

    def get_language_codes(self) -> str: ...

    def save_language_codes(self, language_codes: str) -> Any: ...

    def get_aas_config(self) -> dict[str, Any]: ...

    def save_aas_config(self, config: dict[str, Any]) -> Any: ...

    def upload_video_file(self, channel_folder_name: str, index: int) -> Any: ...

    def create_video(self, channel_folder_name: str, index: int) -> Any: ...

    def add_subtitles_premium(self) -> Any: ...

    def is_aas_checker_running(self) -> bool: ...

    def ensure_aas_checker_running(self) -> bool: ...

    def shutdown(self) -> None: ...
